/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * An identifier for the nomenclatural details of a scientific name
 */
export type TaxonNameIdentifier = string;
/**
 * Full scientific name with author and date
 */
export type TaxonFullName = string;
/**
 * Name of author
 */
export type TaxonNameAuthor = string;
/**
 * Four digit year in which the name was published in
 */
export type TaxonNameYear = number;
/**
 * Full taxon name with author and date, as it appeared in the first publication
 */
export type TaxonNameBrackets = string;

/**
 * Taxon name properties to describe the specimen, author and date
 */
export interface TaxonName {
  taxonNameID: TaxonNameIdentifier;
  taxonFullName: TaxonFullName;
  taxonNameAuthor: TaxonNameAuthor;
  taxonNameYear: TaxonNameYear;
  taxonNameBrackets: TaxonNameBrackets;
  [k: string]: unknown;
}
