/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A numeric, textual value, or reference such as an IRI, that can be used to uniquely identify the object to which it is attached
 */
export type ReferenceCollectionIdentifier = string;
/**
 * A role played by a Person in the context of an entity such as an ObjectGroup, OrganisationalUnit or RecordLevel
 */
export type Creator = string;
/**
 * A role played by a Person in the context of an entity such as an ObjectGroup, OrganisationalUnit or RecordLevel
 */
export type Maintainer = string;
/**
 * Information about rights held in and over the resource
 */
export type CopyrightLicense = string;
/**
 * A person or organization owning or managing rights over the resource
 */
export type CopyrightOwner = string;
/**
 * A name given to the resource
 */
export type Title = string;
/**
 * An account of the resource
 */
export type Description = string;
/**
 * The geographic location from which objects associated with the ObjectGroup were collected, or where an Event took place
 */
export type Area = string[];
/**
 * A higher taxon (e. g., a genus, family, or order) at the level of the genus or higher, that covers all taxa that are the primary subject of the resource (which may be a media item or a collection)
 */
export type IncludedTaxaDescription = string;
/**
 * A language of the resource
 */
export type Language = string;
/**
 * Date on which the resource was changed
 */
export type LastUpdate = string;
/**
 * A (universally) unique identifier for the taxon
 */
export type TaxonIdentifier = string;
/**
 * An identifier for the nomenclatural details of a scientific name
 */
export type TaxonValidNameIdentifier = string;
/**
 * An identifier for the nomenclatural details of a scientific name
 */
export type TaxonNameIdentifier = string;
/**
 * Full scientific name with author and date
 */
export type TaxonFullName = string;
/**
 * Name of author
 */
export type TaxonNameAuthor = string;
/**
 * Four digit year in which the name was published in
 */
export type TaxonNameYear = number;
/**
 * Full taxon name with author and date, as it appeared in the first publication
 */
export type TaxonNameBrackets = string;
/**
 * An identifier for the organism
 */
export type OrganismIdentifier = string;
/**
 * A universally unique identifier for the occurrence
 */
export type OccurrenceIdentifier = string;
/**
 * An unambiguous reference to the media resource
 */
export type MediaIdentifier = string;
/**
 * An identifier for the dwc:Occurrence (as opposed to a particular digital record of the dwc:Occurrence). In the absence of a persistent global unique identifier, construct one from a combination of identifiers in the record that will most closely make the dwc:occurrenceID globally unique
 */
export type DocumentOccurrenceIdentifier = string;
/**
 * Information about rights held in and over the resource
 */
export type CopyrightLicense1 = string;
/**
 * A URI that uniquely identifies a service that provides a representation of the underlying resource
 */
export type MediaDataURL = string;
/**
 * URI for a reviewer
 */
export type Reviewed = string;

/**
 * A virtual reference collection schema for Bombus developed in the ELIXIR Biohackathon 2023
 */
export interface VirtualReferenceCollection {
  virtualReferenceCollectionMetaData: VirtualReferenceCollectionMetaData;
  taxa?: Taxon[];
  [k: string]: unknown;
}
export interface VirtualReferenceCollectionMetaData {
  referenceCollectionID: ReferenceCollectionIdentifier;
  creator?: Creator;
  maintainer?: Maintainer;
  copyrightLicense?: CopyrightLicense;
  copyrightOwner?: CopyrightOwner;
  title: Title;
  description?: Description;
  area?: Area;
  includedTaxaDescription?: IncludedTaxaDescription;
  language?: Language;
  lastUpdate: LastUpdate;
  [k: string]: unknown;
}
/**
 * Generic concept of a taxon for identification
 */
export interface Taxon {
  taxonID: TaxonIdentifier;
  taxonValidNameID: TaxonValidNameIdentifier;
  taxonName?: TaxonName;
  organisms?: Organism[];
  [k: string]: unknown;
}
/**
 * Taxon name properties to describe the specimen, author and date
 */
export interface TaxonName {
  taxonNameID: TaxonNameIdentifier;
  taxonFullName: TaxonFullName;
  taxonNameAuthor: TaxonNameAuthor;
  taxonNameYear: TaxonNameYear;
  taxonNameBrackets: TaxonNameBrackets;
  [k: string]: unknown;
}
/**
 * A particular organism
 */
export interface Organism {
  organismID: OrganismIdentifier;
  occurrences?: Occurrence[];
  [k: string]: unknown;
}
/**
 * An existence of an organism in a particular place at a particular time
 */
export interface Occurrence {
  occurrenceID: OccurrenceIdentifier;
  media?: Media[];
  [k: string]: unknown;
}
export interface Media {
  mediaID: MediaIdentifier;
  documentOccurrenceID: DocumentOccurrenceIdentifier;
  copyrightLicense?: CopyrightLicense1;
  mediaDataURL: MediaDataURL;
  reviewed: Reviewed;
  [k: string]: unknown;
}
